---
- name: copy node-expoter configuration
  template:
    src: node_exporter.j2
    dest: "/etc/sysconfig/node_exporter"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version == "7"

- name: ensure node_exporter is started and enabled at boot
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: node_exporter
  when: ansible_distribution_major_version == "7"