---
- name: include OS-specific variables (RedHat)
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

# tasks file for node-exporter
- name: install node_exporter
  include_tasks: "install-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

- import_tasks: config.yml
  when: ansible_os_family == "RedHat"
  become: yes