---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
  - name: Install python for Ansible
    yum:
      name: "{{ item }}"
      state: installed
    loop:
    - epel-release
    - python
    - python-setuptools
    - python-pip
    become: yes
